codeowners:
- path:  "*"
  owner: "@paketo-buildpacks/java-buildpacks"

package:
  repository:     gcr.io/paketo-buildpacks/azure-application-insights
  register:       true
  registry_token: ${{ secrets.JAVA_BUILDPACK_REGISTRY_TOKEN }}

docker_credentials:
- registry: gcr.io
  username: _json_key
  password: ${{ secrets.JAVA_GCLOUD_SERVICE_ACCOUNT_KEY }}

dependencies:
- id:   azure-application-insights-java
  uses: docker://ghcr.io/paketo-buildpacks/actions/github-release-dependency:main
  with:
    glob:        applicationinsights-agent-.+.jar
    owner:       Microsoft
    pre_release: false
    repository:  ApplicationInsights-Java
    token:       ${{ secrets.GITHUB_TOKEN }}
- id:   azure-application-insights-nodejs
  uses: docker://ghcr.io/paketo-buildpacks/actions/npm-dependency:main
  with:
    package:     applicationinsights
    pre_release: false
